[tool.poetry]
name = "minitron"
version = "0.1.0"
description = ""
authors = ["xrsrke <b3f0cus@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
torch = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
